services:
  - type: web
    runtime: docker
    name: website-app-backend
    plan: free
    region: singapore
    branch: main
    healthCheckPath: /
    autoDeployTrigger: commit
    envVars:
      - key: APP_NAME
        value: Build Bright University
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: RENDER_APP_SECRET
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: MYSQL_ATTR_SSL_CA
        value: /etc/ssl/certs/ca-certificates.crt
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
